name: chi_ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - scikit-learn=1.3.0
  - rdkit=2023.3.2
  - mendeleev=0.10.0
  - openpyxl=3.0.10
  - pandas=1.3.5
  - pip
  - pip:
      - torch-geometric
      - torch-cluster
      - torch-scatter
      - torch-sparse
      - mealpy==2.5.4
      - tqdm==4.66.0
